#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 <magnet uri>"
	exit 1
fi

cd ~/.rtorrent/watch || exit    # set your watch directory here
[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit
echo "d10:magnet-uri${#1}:${1}e" > "meta-${BASH_REMATCH[1]}.torrent"
